name: 'InfluxDB Action'
description: 'Install and configure InfluxDB and the InfluxDB CLI.'
branding:
  icon: 'database'
  color: 'gray-dark'
inputs:
  version:
    description: 'Sets the version of InfluxDB to use (for example: 2.0.7). See https://portal.influxdata.com/downloads/ for versions. latest and nightly are also supported.'
    required: true
  start:
    description: 'Set to false if you only need to use the cli tools without a locally running InfluxDB instance. If this is false, you can ignore the init parameters.'
    required: false
    default: 'true'
  org:
    description: 'The initial Organization of the InfluxDB instance.'
    required: false
    default: 'organization'
  user:
    description: 'The initial User of the InfluxDB instance.'
    required: false
    default: 'user'
  password:
    description: 'The initial Password of the InfluxDB instance.'
    required: false
    default: 'password'
  bucket:
    description: 'The initial Bucket of the InfluxDB instance.'
    required: false
    default: 'bucket'
  token:
    description: 'The initial API Token of the InfluxDB instance'
    required: false
    default: 'token'
runs:
  using: "composite"
  steps:
    - name: Download and Install InfluxDB
      if: runner.os == 'Linux'
      run: |
        export INFLUXDB_VERSION=${{ inputs.version }}
        ${{ github.action_path }}/install.sh
      shell: bash

    - name: Configure InfluxDB
      if: runner.os == 'Linux'
      run: |
        export INFLUXDB_START=${{ inputs.start }}
        export INFLUXDB_ORG=${{ inputs.org }}
        export INFLUXDB_USER=${{ inputs.user }}
        export INFLUXDB_PASSWORD=${{ inputs.password }}
        export INFLUXDB_BUCKET=${{ inputs.bucket }}
        export INFLUXDB_TOKEN=${{ inputs.token }}
        ${{ github.action_path }}/setup.sh
        unset INFLUXDB_PASSWORD
        unset INFLUXDB_TOKEN
      shell: bash

    - name: Download and Install InfluxDB
      if: runner.os == 'Windows'
      run: |
        $INFLUXDB_VERSION = ${{ inputs.version }}
        ${{ github.action_path }}/install.ps1
      shell: pwsh

    - name: Configure InfluxDB
      if: runner.os == 'Linux'
      run: |
        export INFLUXDB_START=${{ inputs.start }}
        export INFLUXDB_ORG=${{ inputs.org }}
        export INFLUXDB_USER=${{ inputs.user }}
        export INFLUXDB_PASSWORD=${{ inputs.password }}
        export INFLUXDB_BUCKET=${{ inputs.bucket }}
        export INFLUXDB_TOKEN=${{ inputs.token }}
        ${{ github.action_path }}/setup.ps1
        unset INFLUXDB_PASSWORD
        unset INFLUXDB_TOKEN
      shell: pwsh
