name: Build

on:
  push:

jobs:
  build-package:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - name: Windows
            os: windows-latest
          # - name: Ubuntu
          #   os: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - name: Install InfluxDB
        uses: ./